name: Reaact app
on: 
    push:
        branches:
            - master
            - main
        paths-ignore:
            - .github/workflows/issues.yml
    pull_request:
        types:
            - opened
    workflow_dispatch:
        inputs:
            environment:
              description: "Environment to deploy to"
              required: true
              default: "staging"

jobs: 
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Cache dependency
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint 
              
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install node
              uses: actions/setup-node@v3
              with: 
                node-version: 18
            - name: Cache dependency
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
            - name: install dependency
              run: npm ci
            - name: test the code
              id: run-test
              run: npm run test
            - name: Upload test report
              if: failure() && steps.run-test.outputs == 'failure'
              uses: actions/upload-artifact@v3
              with: 
                 name: test-report
                 path: test.json
           
    build:
        needs: test
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v3
            - name: install node
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Cache dependency
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
            - name: Install dependency
              run: npm ci
            - name: build project
              run: npm run build
            - name: Deploy
              run: echo 'Deploying......'
            - name: Output event
              run: echo "${{ toJSON(github.event) }}"
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dist-files
                path: dist
                # path: |
                #    dist
                #    package.json

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v4
              with:
                name: dist-files
            - name: list contents
              run: ls
            - name: Finding files
              run: find dist/assets/*.js -type f -execdir echo '{}' ';'
