name: Reusable Deploy
on: workflow_call
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Output information
              uses: actions/download-artifact@v4
              with:
                 name: dist-files
            - name: list contents
              run: |
                ls assets
            - name: Finding files
              run: find assets/*.js -type f -execdir echo '{}' ';'
